openapi: 3.0.0
info: 
  title: sample API
  description: these is the description of the api 
  version: "1"

servers:
  - url: http://localhost:3000
    description: local development
  - url: https://quant-xi.vercel.app/

tags:
  - name: common
paths:
  /health-check:
    get:
      tags:
        - common
      responses:
        200:
          description: everything is good
        500:
          description: something bad happen
  /api/role:
    get:
      security:
      - BearerAuth: []
      tags:
        - role
      responses:
        200:
          description: roles data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResponse'
        500:
          description: internal server error
    post:
      security:
        - BearerAuth: []
      tags:
        - role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: 'a resource is created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createResponse'
        422:
          description: invalid input
        500:
          description: internal server error
  /api/role/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      security:
        - BearerAuth: []
      tags:
        - role
      responses:
        200: 
          description: 'a role'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/findResponse'
        404:
          description: 'not found'
        500:
          description: internal server error
    put:
      security:
        - BearerAuth: []
      tags:
        - role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: 'update a resource'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateResponse'
        422:
          description: "invalid data"
        500:
          description: 'internal server error'
    delete:
      security:
        - BearerAuth: []
      tags:
        - role
      responses:
        200: 
          description: 'deleted a role'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteResponse'
          
        
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    'searchResponse':
      type: object
      properties:
        count:
          type: number
        data:
          type: object 
    'createResponse':
      type: object
      properties:
        _id: 
          type: string
    'deleteResponse':
      type: object
      properties:
        message:
          type: string
    'updateResponse':
      type: object
      properties:
        message:
          type: string
    'findResponse':
      type: object
      properties:
        data:
          type: object